# Generated by Django 4.2.2 on 2023-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pantalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=15)),
                ('talle', models.CharField(max_length=2)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
