# Generated by Django 4.2.2 on 2023-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_calzado_remera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calzado',
            name='talle',
            field=models.IntegerField(),
        ),
    ]
