# Generated by Django 4.2.2 on 2023-06-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_calzado_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calzado',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pantalon',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='remera',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
    ]
