# Generated by Django 4.2.2 on 2023-06-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_calzado_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calzado',
            name='marca',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pantalon',
            name='marca',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='remera',
            name='marca',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
