# Generated by Django 4.2.2 on 2023-07-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_calzado_marca_pantalon_marca_remera_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calzado',
            name='marca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pantalon',
            name='marca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='remera',
            name='marca',
            field=models.CharField(max_length=10),
        ),
    ]
