# Generated by Django 4.2.2 on 2023-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_calzado_marca_alter_pantalon_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calzado',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pantalon',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='remera',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
