# Generated by Django 4.2.2 on 2023-07-08 17:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_calzado_descripcion_pantalon_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calzado',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='pantalon',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='remera',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
