# Generated by Django 4.2.2 on 2023-07-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_alter_calzado_descripcion_alter_pantalon_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantalon',
            name='fecha_publicacion',
            field=models.DateTimeField(null=True),
        ),
    ]
