# Generated by Django 4.2.2 on 2023-07-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_pantalon_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantalon',
            name='fecha_publicacion',
        ),
    ]
