# Generated by Django 4.2.2 on 2023-07-08 21:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_remove_pantalon_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calzado',
            name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='calzado',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
