# Generated by Django 4.2.2 on 2023-07-08 22:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_remove_calzado_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calzado',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
