# Generated by Django 4.2.2 on 2023-07-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_alter_calzado_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calzado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='calzados'),
        ),
        migrations.AddField(
            model_name='pantalon',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pantalones'),
        ),
        migrations.AddField(
            model_name='remera',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='remeras'),
        ),
    ]
