# Generated by Django 4.2.2 on 2023-07-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_alter_calzado_imagen_alter_pantalon_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantalon',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pantalones'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='remeras'),
        ),
    ]
