# Generated by Django 4.2.2 on 2023-07-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0016_alter_pantalon_imagen_alter_remera_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calzado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='calzados'),
        ),
    ]
