# Generated by Django 4.2.2 on 2023-07-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0017_alter_calzado_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='calzado',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pantalon',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
