# Generated by Django 4.2.2 on 2023-07-09 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_infoextra_link_web_infoextra_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoextra',
            old_name='Link_web',
            new_name='link_web',
        ),
    ]
